# Generated by Django 3.1.7 on 2021-03-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210325_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='Users.Role'),
        ),
    ]
